# JWT Configuration
spring.application.name=sb-ecommerce
spring.app.issuer=sb-ecommerce-app
spring.app.expiration=10m
spring.app.jwt-cookie=SpringBootEcom
spring.app.cookie-secure=true
spring.app.secret=${JWT_SECRET}

# Database Configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA Basic Configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.highlight_sql=true


# Pagination Default values
spring.data.web.pageable.default-page-size=10
spring.data.web.pageable.one-indexed-parameters=false

# Product image upload path
app.upload.dir=images

# Problem Details Configuration
spring.mvc.problemdetails.enabled=true

